apiVersion: v1
kind: Service
metadata:
  name: selenoid-ui
spec:
  selector:
    app: selenoid-ui
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.selenoidUi.port }}
      targetPort: {{ .Values.selenoidUi.port }}
  type: NodePort
