apiVersion: v1
kind: Service
metadata:
  name: selenoid
spec:
  selector:
    app: selenoid
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.selenoid.port }}
      targetPort: {{ .Values.selenoid.port }}
  type: NodePort
